import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import shap
from sklearn.ensemble import RandomForestRegressor
import os
from typing import List, Tuple, Optional

class ExplainabilityEngine:
    """
    XAI Engine that trains a surrogate RandomForest model on the same windowed features
    to explain the forecasting logic using SHAP values (Summary, Waterfall, and Force plots).
    """
    def __init__(self, n_estimators: int = 50):
        self.surrogate_model = RandomForestRegressor(n_estimators=n_estimators, random_state=42)
        self.explainer: Optional[shap.TreeExplainer] = None
        self.feature_names: List[str] = []
        self.is_fitted = False

    def _flatten_data(self, X: np.ndarray, feature_cols: List[str]) -> Tuple[np.ndarray, List[str]]:
        """
        Flattens 3D sequences (samples, lookback, features) to 2D tabular features for the surrogate model.
        """
        samples, lookback, n_feats = X.shape
        X_flat = X.reshape(samples, lookback * n_feats)
        
        # Generate descriptive names, e.g., confirmed_cases_t-14, mobility_index_t-1
        flat_feature_names = []
        for t in range(lookback):
            offset = lookback - t
            for f in feature_cols:
                flat_feature_names.append(f"{f}_t-{offset}")
                
        return X_flat, flat_feature_names

    def fit(self, X_train: np.ndarray, y_train: np.ndarray, feature_cols: List[str]) -> 'ExplainabilityEngine':
        """
        Trains the RandomForest surrogate model and fits the SHAP TreeExplainer.
        """
        print("Training surrogate RandomForest model for explainability...")
        X_flat, self.feature_names = self._flatten_data(X_train, feature_cols)
        
        # Fit random forest
        self.surrogate_model.fit(X_flat, y_train)
        
        # Fit SHAP explainer
        self.explainer = shap.TreeExplainer(self.surrogate_model)
        self.is_fitted = True
        return self

    def generate_plots(self, X_test: np.ndarray, feature_cols: List[str], output_dir: str = "models/explainability") -> None:
        """
        Generates and saves the 3 SHAP plots: Summary, Waterfall, and Force.
        """
        if not self.is_fitted or self.explainer is None:
            raise ValueError("Engine must be fitted before generating explanations.")
            
        os.makedirs(output_dir, exist_ok=True)
        X_flat, _ = self._flatten_data(X_test, feature_cols)
        
        # Calculate SHAP values
        print("Calculating SHAP values...")
        # To speed up and avoid huge memory usage, we take a subset for explainer values
        subset_size = min(100, len(X_flat))
        X_subset = X_flat[:subset_size]
        
        # Calculate explanation object for plots
        shap_explanation = self.explainer(X_subset)
        
        # 1. SHAP Summary Plot
        plt.figure(figsize=(10, 6))
        # We limit max_display to show the top 15 most important features clearly
        shap.summary_plot(shap_explanation.values, X_subset, feature_names=self.feature_names, max_display=15, show=False)
        plt.title("SHAP Feature Importance Summary", fontsize=14, pad=15)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "shap_summary.png"), dpi=150, bbox_inches="tight")
        plt.close()
        
        # 2. Local Waterfall Plot (for instance 0)
        plt.figure(figsize=(10, 6))
        # Ensure we have correct shape/explanation object
        shap.plots.waterfall(shap_explanation[0], max_display=10, show=False)
        plt.title("SHAP Waterfall: Outbreak Prediction Breakdown", fontsize=14, pad=15)
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, "shap_waterfall.png"), dpi=150, bbox_inches="tight")
        plt.close()
        
        # 3. Local Force Plot (for instance 0)
        # Note: force plot in matplotlib can be generated by calling shap.plots.force
        plt.figure(figsize=(12, 4))
        try:
            # Generate force plot using standard force plot matplotlib renderer
            shap.force_plot(
                self.explainer.expected_value, 
                shap_explanation.values[0], 
                X_subset[0], 
                feature_names=self.feature_names, 
                matplotlib=True, 
                show=False
            )
            plt.title("SHAP Force Plot: Local Prediction Forces", fontsize=14, pad=20)
            plt.tight_layout()
            plt.savefig(os.path.join(output_dir, "shap_force.png"), dpi=150, bbox_inches="tight")
        except Exception as e:
            # Fallback if force plot fails due to backend/matplotlib conflicts
            print(f"Force plot failed: {e}. Generating fallback feature contribution bar chart.")
            plt.figure(figsize=(10, 5))
            contribs = shap_explanation.values[0]
            indices = np.argsort(np.abs(contribs))[-10:]
            plt.barh(np.array(self.feature_names)[indices], contribs[indices], color=['red' if c > 0 else 'blue' for c in contribs[indices]])
            plt.xlabel("SHAP Value (Impact on Prediction)")
            plt.title("Local Feature Contributions (Force Plot Alternative)")
            plt.tight_layout()
            plt.savefig(os.path.join(output_dir, "shap_force.png"), dpi=150)
        finally:
            plt.close()
            
        print(f"SHAP plots successfully saved to {output_dir}")
